### ISSUE TITLE
some class not found

### ISSUE THREAD

**Issue by liguoqinjim** [Terasology/PolyWorld#13]
where can i find the 'org.terasology.math.geom.*' package?

**Comment by Cervator** [comment]
Hi @liguoqinjim - we have several libraries that the game and in turn modules depend on. You're probably looking for our math library TeraMath?

https://github.com/MovingBlocks/TeraMath/tree/develop/src/main/java/org/terasology/math/geom

So long as you run `gradlew` an additional time (probably `gradlew idea` to then also generate project files for IntelliJ) you should be getting all required dependencies automatically. Are you hitting any compile-time problems?
