### ISSUE TITLE
Isolated rivers 

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/PolyWorld#2]
Rivers can occur isolated on the islands, without being connected to any other water body (e.g., ocean, lake, or another river). Is it possibly due to the river model getting stuck at a local minimum of the elevation model?
![pw_rivers](https://cloud.githubusercontent.com/assets/1448874/6620900/b7af5926-c8d3-11e4-87b0-211ee9a68fd7.JPG)

**Comment by msteiger** [comment]
That's odd, but it seems like it. Not sure how that's possible, since elevation increases gradually from the sea shore. Maybe it cannot find away from the "flat" lake. Where did you find this island (world coordinates)?

**Comment by skaldarnar** [comment]
Oh, need to check (and probably search) again. I thought I'd captured the info overlay in the screenshot as well. They do not occur very frequently, but I discovered some more cases over the testing runs.

**Comment by msteiger** [comment]
Fixed in 4ae1d396bdaa1454b862b
