### ISSUE TITLE
Rename class Region to GraphRegion

### ISSUE THREAD

**Issue by meetcshah19** [Terasology/PolyWorld#24]
The naming Region clashes with another class in the engine and GraphRegion is more accurate to describe what the class is about.

**Comment by gaurav9822** [comment]
@meetcshah19  @jdrueckert  can I take this issue?

**Comment by meetcshah19** [comment]
Yes @gaurav9822

**Comment by jdrueckert** [comment]
@gaurav9822 Actually we already have somebody working on this (see https://github.com/Terasology/PolyWorld/pull/26). However as mentioned in the linked there's a second PR in `Lost` required to fully support this. So if you'd like you can take that.

**Comment by skaldarnar** [comment]
Fixed by #26
