### ISSUE TITLE
How to run it

### ISSUE THREAD

**Issue by flagflag** [Terasology/PolyWorld#45]

**Comment by Cervator** [comment]
Hi there @flagflag - this is a "library" module to help make specific world generators, you don't run it by itself :-)

A few other worlds over time has been based on this approach, but I'm not sure which if any currently work. I believe https://github.com/Terasology/Lost is one of them and was working nicely some time back. You would make sure that's present along with all its dependencies then look for the right gameplay template and world to pick it.

Closing this as answered
