### ISSUE TITLE
Broken Voronoi diagram

### ISSUE THREAD

**Issue by msteiger** [Terasology/PolyWorld#9]
Location: 630 / -220
Seed: a
Graph Density: 3.7
WorldGen: Island World

![image](https://cloud.githubusercontent.com/assets/1820007/9149818/804ca9f8-3dbc-11e5-9afe-a542a7e1bb28.png)

**Comment by jdrueckert** [comment]
@meetcshah19 While working on and with `PolyWorld`, did you come across anything like that?
